name: flutter_stetho
description: A new flutter plugin project.
version: 0.0.1
author: Brian Egan <brian@brianegan.com>
homepage: https://github.com/brianegan/flutter_stetho

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.brianegan.flutterstetho
    pluginClass: FlutterStethoPlugin
